name: qwen_dms
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - streamlit
      - fastapi
      - uvicorn
      - python-multipart
      - openai
      - pypdf2
      - sentence-transformers
      - chromadb
      - pymupdf
      - numpy
      - requests
